### ISSUE TITLE
Localização do exercício 03

### ISSUE THREAD

**Issue by fabriciofx** [ClaraFontes/DSW1#10]
@ClaraFontes você fez o exercício 03? Se sim, em qual diretório ele se encontra?

**Comment by ClaraFontes** [comment]
Oi, professor! Não fiz o exercício 3.

**Comment by fabriciofx** [comment]
@ClaraFontes ok!

**Comment by ClaraFontes** [comment]
@fabriciofx, fiz e adicionei no github pages o exercício 3. Ok?

**Comment by fabriciofx** [comment]
@ClaraFontes ok!
