### ISSUE TITLE
Quebras de linhas desnecessárias

### ISSUE THREAD

**Issue by fabriciofx** [ClaraFontes/DSW1#2]
Existem quebras de linhas desnecessárias como no `<head>` da página `home.html`. É importante revisar todos os arquivos com relação a isso.

**Comment by ClaraFontes** [comment]
Quebra de linhas removidas!

**Comment by ClaraFontes** [comment]
Removi as quebras de linha, @fabriciofx.

**Comment by fabriciofx** [comment]
@ClaraFontes agora está ok!
