### ISSUE TITLE
Adicionar footer nas páginas onde for necessário

### ISSUE THREAD

**Issue by fabriciofx** [ClaraFontes/DSW1#3]
Adicionar um `<footer>` nas páginas onde for necessário. Revisar todos os arquivos.

**Comment by ClaraFontes** [comment]
Adicionado.

**Comment by ClaraFontes** [comment]
Adicionei. @fabriciofx, verifique se tá ok.

**Comment by fabriciofx** [comment]
@ClaraFontes ok!
